project:
  type: chribel-summary-quarto
  render: 
    - template_project.qmd

format:
  chribel-summary-quarto-pdf:
    include-in-header:
    - text: "\\usepackage[datesep=.]{datetime2}"
    - text: "\\DTMsetdatestyle{ddmmyyyy}"
    - text: "\\usepackage{blindtext}"
    toc: true
    classoption: twocolumn

# [DOCUMENT INFORMATION]
title: "A Summary Title"
subtitle: "Summary"
author: "Me, the cool author blablablablablabla"

# [PAGE OPTIONS]
lang: de-CH
babel-lang: nswissgerman

# [HEADER & FOOTER]
fancyhdr:
  header:
    right: "You're reading a summary"
    center: ""
    left: "Monkey University"
  footer:
    right: "Monkey Course"
    center: "\\thepage\\ / \\pageref{LastPage}"
    left: "\\today"

source:
  github: "https://www.youtube.com/watch?v=VGhcSupkNs8"